config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, to: "follows#following"
         get :followers, to: "follows#followers"
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t(".footer_info"), Settings.footer.tutorial, target: :_blank %> by <%=
    link_to "Michael Hartl", Settings.footer.author, target: :_blank %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), help_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li><%= link_to t(".news"), Settings.footer.tutorial, target: :_blank %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li><%= link_to t(".home"), root_path %></li>
          <li><%= link_to t(".help"), help_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), user_path(current_user) %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= button_to t(".log_out"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
   <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
   </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <% javascript_include_tag "i18n" %>
      <% javascript_include_tag "translations", skip_pipeline: true %>
      <title><%= full_title yield(:title) %></title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag "application", media: "all",
        "data-turbolinks-track": "reload" %>
      <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
      <%= render "layouts/shim" %>
    </head>
    <body>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= render "layouts/header" %>
      <div class="container">
        <%= yield %>
      </div>
      <script type = "text/javascript">
        I18n.defaultLocale = "<%= I18n.default_locale %>";
        I18n.locale = "<%= I18n.locale %>";
      </script>
    </body>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
    <%= debug(params) if Rails.env.development? %>
</html>